version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.15
  working_directory: /go/src/github.com/krzysztofreczek/go-structurizr

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: go mod vendor
      - run: go test -v ./...
      - run: go build ./...
  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} v0.0.${CIRCLE_BUILD_NUM}

workflows:
  version: 2
  build-release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
              
